issue: Check that new issues are opened by organization members

on:
  issues:
    types: [opened]

jobs:
  orgcheck:
    name: Check that the issue author is in the uf-mil org
    runs-on: ubuntu-latest
    steps:
      - name: Query the GitHub API
        uses: JamesSingleton/is-organization-member@1.0.0
        id: is_organization_member
        with:
          organization: uf-mil
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.INVESTIGATOR_BOT_TOKEN }}
      - name: Close if necessary
        if: steps.is_organization_member.outputs.result == 'false'
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            @${{ github.event.issue.user.login }}, hola from the [Machine Intelligence Lab at the University of Florida](https://mil.ufl.edu)!

            Unfortunately, at this time, we are unable to accept issues and contributions to this repository from users who are not yet part of MIL. We may accept contributions in the future, and some of our other repositories and projects accept contributions. However, because much of our lab is dependent on this repository and because we use several in-house tools to ensure that new additions work properly, we are unable to easily accept the contributions from researchers outside of MIL.

            _If you are a member of MIL, please contact a software leader to get access to the @uf-mil organization._
          token: ${{ secrets.INVESTIGATOR_BOT_TOKEN }}
